# Generated by Django 5.2.3 on 2025-11-19 09:08

import collections
import jsonfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("config", "0060_alter_device_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="config",
            name="test_case_context",
            field=jsonfield.fields.JSONField(
                blank=True,
                default=dict,
                dump_kwargs={"ensure_ascii": False, "indent": 4},
                help_text="use for connected devices",
                load_kwargs={"object_pairs_hook": collections.OrderedDict},
                null=True,
            ),
        ),
    ]
