# Generated by Django 5.2.3 on 2025-11-24 07:19

import collections
import jsonfield.fields
import pathlib
import private_storage.fields
import private_storage.storage.files
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("config", "0061_config_test_case_context"),
    ]

    operations = [
        migrations.AddField(
            model_name="config",
            name="file",
            field=private_storage.fields.PrivateFileField(
                blank=True,
                help_text="Input for test cases",
                max_length=255,
                null=True,
                storage=private_storage.storage.files.PrivateFileSystemStorage(
                    base_url="/test-script-media/",
                    location=pathlib.PurePosixPath(
                        "/home/spanidea-lt83/Desktop/nokia/openwisp-controller/tests/media/tmp"
                    ),
                ),
                upload_to="",
                verbose_name="Test Script",
            ),
        ),
        migrations.AlterField(
            model_name="config",
            name="test_case_context",
            field=jsonfield.fields.JSONField(
                blank=True,
                default=dict,
                dump_kwargs={"ensure_ascii": False, "indent": 4},
                help_text="Use for connected devices",
                load_kwargs={"object_pairs_hook": collections.OrderedDict},
                null=True,
            ),
        ),
    ]
