# Generated by Django 5.2.3 on 2025-11-26 09:23

import collections
import jsonfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("config", "0061_config_test_case_context"),
    ]

    operations = [
        migrations.AlterField(
            model_name="config",
            name="test_case_context",
            field=jsonfield.fields.JSONField(
                blank=True,
                default=dict,
                dump_kwargs={"ensure_ascii": False, "indent": 4},
                help_text="Test Case Configuration",
                load_kwargs={"object_pairs_hook": collections.OrderedDict},
                null=True,
            ),
        ),
    ]
