# Generated by Django 5.2.3 on 2026-01-12 06:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("config", "0062_alter_config_test_case_context"),
        ("config", "0063_remove_config_file_alter_config_test_case_context"),
    ]

    operations = []
