# Generated by Django 5.2.3 on 2026-01-16 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("config", "0064_merge_20260107_2319"),
        ("config", "0064_merge_20260112_1139"),
    ]

    operations = []
