# Generated by Django 5.2.3 on 2026-01-18 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("config", "0065_merge_20260116_1822"),
        ("config", "0065_merge_20260117_1710"),
    ]

    operations = []
