# Generated by Django 5.2.3 on 2026-01-23 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("config", "0066_merge_20260118_2309"),
    ]

    operations = [
        migrations.AddField(
            model_name="device",
            name="deleted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="device",
            name="is_deleted",
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
