# Generated by Django 5.2.3 on 2026-01-27 04:18

import django.core.validators
import openwisp_utils.fields
import re
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("config", "0067_device_deleted_at_device_is_deleted"),
        ("openwisp_users", "0021_rename_user_id_email_openwisp_us_id_06c07a_idx"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="device",
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name="device",
            name="key",
            field=openwisp_utils.fields.KeyField(
                blank=True,
                db_index=True,
                default=None,
                help_text="unique device key",
                max_length=64,
                validators=[
                    django.core.validators.RegexValidator(
                        re.compile("^[^\\s/\\.]+$"),
                        code="invalid",
                        message="This value must not contain spaces, dots or slashes.",
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="device",
            name="name",
            field=models.CharField(
                db_index=True,
                help_text="must be either a valid hostname or mac address",
                max_length=64,
                validators=[
                    django.core.validators.RegexValidator(
                        re.compile(
                            "^([a-zA-Z0-9]|[a-zA-Z0-9][a-zA-Z0-9\\-]{0,61}[a-zA-Z0-9])(\\.([a-zA-Z0-9]|[a-zA-Z0-9][a-zA-Z0-9\\-]{0,61}[a-zA-Z0-9]))*$|^([0-9A-Fa-f]{2}[:-]){5}([0-9A-Fa-f]{2})$"
                        ),
                        code="invalid",
                        message="Must be either a valid hostname or mac address.",
                    )
                ],
            ),
        ),
        migrations.AddConstraint(
            model_name="device",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_deleted", False)),
                fields=("name",),
                name="unique_device_name_alive",
            ),
        ),
        migrations.AddConstraint(
            model_name="device",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_deleted", False), ("key__isnull", False)),
                fields=("key",),
                name="unique_device_key_alive_not_null",
            ),
        ),
        migrations.AddConstraint(
            model_name="device",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_deleted", False)),
                fields=("mac_address", "organization"),
                name="unique_mac_org_alive",
            ),
        ),
        migrations.AddConstraint(
            model_name="device",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_deleted", False)),
                fields=("hardware_id", "organization"),
                name="unique_hardware_org_alive",
            ),
        ),
    ]
