# NOTE: This Docker image is for development purposes only.

services:
  controller:
    image: openwisp/controller-development:latest
    environment:
      - REDIS_URL=redis://redis:6379
    build:
      context: .
    ports:
      - 8000:8000
    depends_on:
      - redis
      - postgres
      - influxdb

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    entrypoint: redis-server --appendonly yes
    volumes:
      - redis_data:/data

  postgres:
    image: postgis/postgis:17-3.5-alpine
    environment:
      POSTGRES_PASSWORD: openwisp2
      POSTGRES_USER: openwisp2
      POSTGRES_DB: openwisp2
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data

# monitoring
  influxdb:
    image: influxdb:1.8-alpine
    volumes:
      - influxdb-data:/var/lib/influxdb
      - ./tests/influxdb.conf:/etc/influxdb/influxdb.conf
    ports:
      - "8086:8086"
      - "8089:8089/udp"
      - "8090:8090/udp"
      - "8091:8091/udp"
      - "8092:8092/udp"
    environment:
      INFLUXDB_DB: openwisp2
      INFLUXDB_USER: openwisp
      INFLUXDB_USER_PASSWORD: openwisp  


volumes:
  redis_data:
  postgres_data:
  influxdb-data: {}

