# NOTE: This Docker image is for production purposes only.

services:



  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/openwisp.conf:/etc/nginx/conf.d/default.conf
      - ./logs/nginx:/var/log/nginx
    depends_on:
      - controller
    restart: unless-stopped


    
  controller:
    image: openwisp/controller-production:latest
    environment:
      - REDIS_URL=redis://redis:6379
    build:
      context: .
      args:
        GIT_USER: ${GIT_USER}
        GIT_TOKEN: ${GIT_TOKEN}
    env_file:
      - .env
    ports:
      - "${APP_PORT}:${APP_PORT}"
    depends_on:
      - redis
      - postgres
      - influxdb
    # Override the command to only run Django server
    command: sh /opt/openwisp/tests/docker-entrypoint.sh
    volumes:
      - ./:/opt/openwisp
      - ./logs:/opt/openwisp/logs
      # Mount Django project for hot reload
      # Add firmware and media volumes (in case beat tasks need access)
      - ./media:/opt/openwisp/media:rw
      - openwisp_private_storage:/opt/openwisp/private/firmware

  celery-worker:
    image: openwisp/controller-production:latest
    environment:
      - REDIS_URL=redis://redis:6379
    build:
      context: .
      args:
        GIT_USER: ${GIT_USER}
        GIT_TOKEN: ${GIT_TOKEN}
    env_file:
      - .env  
    depends_on:
      - redis
      - postgres
      - influxdb
      - controller  # Wait for migrations to complete
    command: celery -A openwisp2 worker -l info

    # No ports needed for worker
    volumes:

      - ./:/opt/openwisp  # Share the same code volume if needed
      - ./logs:/opt/openwisp/logs
      # Add firmware and media volumes (in case beat tasks need access)
      - ./media:/opt/openwisp/media:rw
      - openwisp_private_storage:/opt/openwisp/private/firmware
      

  celery-beat:
    image: openwisp/controller-production:latest
    environment:
      - REDIS_URL=redis://redis:6379
    build:
      context: .
      args:
        GIT_USER: ${GIT_USER}
        GIT_TOKEN: ${GIT_TOKEN}
    env_file:
       - .env  
    depends_on:
      - redis
      - postgres
      - influxdb
      - controller  # Wait for migrations to complete
    command: celery -A openwisp2 beat -l info --schedule /opt/openwisp/tests/openwisp2/celerybeat-schedule
    # No ports needed for beat
    volumes:
      - ./:/opt/openwisp  # Share the same code volume if needed
      - ./logs:/opt/openwisp/logs
      # Add firmware and media volumes (in case beat tasks need access)
      - ./media:/opt/openwisp/media:rw
      - openwisp_private_storage:/opt/openwisp/private/firmware
      

  redis:
    image: redis:alpine
    restart: always
    command: ["redis-server", "--appendonly", "yes", "--appendfsync", "everysec", "--save", ""]
    # ports:
    #   - "6379:6379"
    volumes:
      - redis_data:/data

  postgres:
    image: postgis/postgis:17-3.5-alpine
    restart: always
    environment:
      - POSTGRES_PASSWORD=$DB_PASS
      - POSTGRES_USER=$DB_USER
      - POSTGRES_DB=$DB_NAME
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # monitoring
  influxdb:
    image: influxdb:1.8-alpine
    restart: always
    volumes:
      - influxdb_data:/var/lib/influxdb
      - ./tests/influxdb.conf:/etc/influxdb/influxdb.conf
    ports:
      - "8086:8086"
      - "8089:8089/udp"
      - "8090:8090/udp"
      - "8091:8091/udp"
      - "8092:8092/udp"
    environment:
      - INFLUXDB_DB=$INFLUXDB_NAME
      - INFLUXDB_USER=$INFLUXDB_USER
      - INFLUXDB_USER_PASSWORD=$INFLUXDB_PASS



volumes:
  redis_data: {}
  postgres_data: {}
  influxdb_data: {}
  logs: {}
  # Add new volumes for firmware and media storage
  media_data: {}
  openwisp_private_storage: {}

