# Generated by Django 5.2.3 on 2025-06-23 10:47

import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
import openwisp_users.mixins
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("openwisp_users", "0021_rename_user_id_email_openwisp_us_id_06c07a_idx"),
    ]

    operations = [
        migrations.CreateModel(
            name="TestCategory",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        db_index=True,
                        help_text="Category name to group related test cases",
                        max_length=64,
                        verbose_name="name",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        blank=True,
                        help_text="Optional code for this category",
                        max_length=64,
                        verbose_name="code",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Detailed description of what tests in this category do",
                        verbose_name="description",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="openwisp_users.organization",
                        verbose_name="organization",
                    ),
                ),
            ],
            options={
                "verbose_name": "Test Category",
                "verbose_name_plural": "Test Categories",
                "ordering": ["name"],
                "abstract": False,
                "swappable": "TEST_MANAGEMENT_TESTCATEGORY_MODEL",
                "unique_together": {("name", "organization")},
            },
            bases=(openwisp_users.mixins.ValidateOrgMixin, models.Model),
        ),
        migrations.CreateModel(
            name="TestCase",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        db_index=True,
                        help_text="Descriptive name for the test case",
                        max_length=128,
                        verbose_name="test case name",
                    ),
                ),
                (
                    "test_case_id",
                    models.CharField(
                        db_index=True,
                        help_text="Unique identifier used by devices to execute this test",
                        max_length=64,
                        verbose_name="test case ID",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Detailed description of what this test does",
                        verbose_name="description",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Whether this test case is currently active",
                        verbose_name="is active",
                    ),
                ),
                (
                    "parameters",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Optional parameters for test execution",
                        verbose_name="parameters",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        help_text="Category this test case belongs to",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="test_cases",
                        to=settings.TEST_MANAGEMENT_TESTCATEGORY_MODEL,
                        verbose_name="category",
                    ),
                ),
            ],
            options={
                "verbose_name": "Test Case",
                "verbose_name_plural": "Test Cases",
                "ordering": ["category", "name"],
                "abstract": False,
                "swappable": "TEST_MANAGEMENT_TESTCASE_MODEL",
                "indexes": [
                    models.Index(
                        fields=["test_case_id"], name="test_manage_test_ca_8bd6aa_idx"
                    ),
                    models.Index(
                        fields=["category", "name"],
                        name="test_manage_categor_8b88a5_idx",
                    ),
                ],
                "unique_together": {("category", "name")},
            },
        ),
    ]
