# Generated by Django 5.2.3 on 2025-07-01 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("test_management", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="testcase",
            name="test_type",
            field=models.IntegerField(
                choices=[(1, "Robot Framework"), (2, "Agent")],
                default=1,
                help_text="Type of test: Robot Framework or Agent ",
                verbose_name="test type",
            ),
        ),
    ]
