# Generated by Django 5.2.3 on 2025-06-23 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("test_management", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="testcategory",
            name="code",
            field=models.CharField(
                blank=True,
                help_text="Optional code for this category",
                max_length=64,
                verbose_name="code",
            ),
        ),
    ]
