# Generated by Django 5.2.3 on 2025-06-25 04:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("test_management", "0002_remove_testsuitecase_permissions"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="testsuitecase",
            options={
                "default_permissions": (),
                "ordering": ["test_suite", "order", "test_case"],
                "verbose_name": "Test Suite Case",
                "verbose_name_plural": "Test Suite Cases",
            },
        ),
    ]
