# Generated by Django 5.2.3 on 2025-07-03 12:14

import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("test_management", "0002_alter_testcase_test_type"),
        migrations.swappable_dependency(settings.CONFIG_DEVICE_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="TestCaseExecution",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                (
                    "started_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When this test case execution started",
                        null=True,
                        verbose_name="started at",
                    ),
                ),
                (
                    "completed_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When this test case execution completed",
                        null=True,
                        verbose_name="completed at",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("running", "Running"),
                            ("success", "Success"),
                            ("failed", "Failed"),
                            ("timeout", "Timeout"),
                            ("cancelled", "Cancelled"),
                        ],
                        db_index=True,
                        default="pending",
                        help_text="Current execution status",
                        max_length=20,
                        verbose_name="status",
                    ),
                ),
                (
                    "execution_order",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Order in which this test case should be executed within the suite",
                        verbose_name="execution order",
                    ),
                ),
                (
                    "exit_code",
                    models.IntegerField(
                        blank=True,
                        help_text="Exit code returned by the test execution",
                        null=True,
                        verbose_name="exit code",
                    ),
                ),
                (
                    "stdout",
                    models.TextField(
                        blank=True,
                        help_text="Standard output from test execution",
                        verbose_name="standard output",
                    ),
                ),
                (
                    "stderr",
                    models.TextField(
                        blank=True,
                        help_text="Standard error output from test execution",
                        verbose_name="standard error",
                    ),
                ),
                (
                    "result_data",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Additional structured result data (JSON format)",
                        verbose_name="result data",
                    ),
                ),
                (
                    "execution_duration",
                    models.DurationField(
                        blank=True,
                        help_text="Total time taken for test execution",
                        null=True,
                        verbose_name="execution duration",
                    ),
                ),
                (
                    "error_message",
                    models.TextField(
                        blank=True,
                        help_text="Error message if execution failed",
                        verbose_name="error message",
                    ),
                ),
                (
                    "retry_count",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Number of times this test case execution was retried",
                        verbose_name="retry count",
                    ),
                ),
                (
                    "device",
                    models.ForeignKey(
                        help_text="Device where this test case was executed",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="test_case_executions",
                        to=settings.CONFIG_DEVICE_MODEL,
                        verbose_name="device",
                    ),
                ),
                (
                    "test_case",
                    models.ForeignKey(
                        help_text="The test case that was executed",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="executions",
                        to=settings.TEST_MANAGEMENT_TESTCASE_MODEL,
                        verbose_name="test case",
                    ),
                ),
                (
                    "test_suite_execution",
                    models.ForeignKey(
                        help_text="The parent test suite execution",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="test_case_executions",
                        to=settings.TEST_MANAGEMENT_TESTSUITEEXECUTION_MODEL,
                        verbose_name="test suite execution",
                    ),
                ),
            ],
            options={
                "verbose_name": "Test Case Execution",
                "verbose_name_plural": "Test Case Executions",
                "ordering": ["test_suite_execution", "device", "execution_order"],
                "abstract": False,
                "swappable": "TEST_MANAGEMENT_TESTCASEEXECUTION_MODEL",
                "indexes": [
                    models.Index(
                        fields=["test_suite_execution", "device"],
                        name="test_manage_test_su_271b38_idx",
                    ),
                    models.Index(
                        fields=["status", "started_at"],
                        name="test_manage_status_2bc99b_idx",
                    ),
                    models.Index(
                        fields=["test_case", "status"],
                        name="test_manage_test_ca_7e8c36_idx",
                    ),
                ],
                "unique_together": {("test_suite_execution", "device", "test_case")},
            },
        ),
    ]
