# Generated by Django 5.2.3 on 2025-07-22 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("test_management", "0003_testcaseexecution"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="testcaseexecution",
            options={
                "default_permissions": (),
                "ordering": ["test_suite_execution", "device", "execution_order"],
                "verbose_name": "Test Case Execution",
                "verbose_name_plural": "Test Case Executions",
            },
        ),
        migrations.AlterModelOptions(
            name="testsuiteexecutiondevice",
            options={
                "default_permissions": (),
                "ordering": ["test_suite_execution", "device"],
                "verbose_name": "Test Suite Execution Device",
                "verbose_name_plural": "Test Suite Execution Devices",
            },
        ),
        migrations.AddField(
            model_name="testcase",
            name="params",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Optional parameters for test execution in JSON format. These parameters can be used to customize test case behavior.",
                verbose_name="parameters",
            ),
        ),
    ]
