# Generated by Django 5.2.3 on 2025-08-06 09:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("test_management", "0004_alter_testcaseexecution_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="testsuite",
            options={
                "ordering": ["name"],
                "verbose_name": "Test Group",
                "verbose_name_plural": "Test Groups",
            },
        ),
        migrations.AlterModelOptions(
            name="testsuitecase",
            options={
                "default_permissions": (),
                "ordering": ["test_suite", "order", "test_case"],
                "verbose_name": "Test Group Case",
                "verbose_name_plural": "Test Group Cases",
            },
        ),
        migrations.AlterModelOptions(
            name="testsuiteexecution",
            options={
                "ordering": ["-created"],
                "verbose_name": "Test Group Execution",
                "verbose_name_plural": "Test Executions",
            },
        ),
        migrations.AlterUniqueTogether(
            name="testsuite",
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name="testcase",
            name="category",
            field=models.ForeignKey(
                help_text="Category this test case belongs to",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="test_cases",
                to=settings.TEST_MANAGEMENT_TESTCATEGORY_MODEL,
                verbose_name="Select Test Category",
            ),
        ),
        migrations.AlterField(
            model_name="testcase",
            name="description",
            field=models.TextField(
                blank=True,
                help_text="Detailed description of what this test does",
                verbose_name="Description",
            ),
        ),
        migrations.AlterField(
            model_name="testcase",
            name="is_active",
            field=models.BooleanField(
                default=True,
                help_text="Whether this test case is currently active",
                verbose_name="Is Active",
            ),
        ),
        migrations.AlterField(
            model_name="testcase",
            name="name",
            field=models.CharField(
                db_index=True,
                help_text="Descriptive name for the test case",
                max_length=50,
                verbose_name="Test Case",
            ),
        ),
        migrations.AlterField(
            model_name="testcase",
            name="params",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Optional parameters for test case execution in JSON format. These parameters can be used to customize test case behavior.",
                verbose_name="Parameters",
            ),
        ),
        migrations.AlterField(
            model_name="testcase",
            name="test_case_id",
            field=models.CharField(
                db_index=True,
                help_text="Unique identifier used by devices to execute this test",
                max_length=50,
                unique=True,
                verbose_name="Test Case ID",
            ),
        ),
        migrations.AlterField(
            model_name="testcase",
            name="test_type",
            field=models.IntegerField(
                choices=[(1, "Robot Framework"), (2, "Device Agent")],
                default=1,
                help_text="Type of test: Robot Framework or Device Agent ",
                verbose_name="Test Type",
            ),
        ),
        migrations.AlterField(
            model_name="testcategory",
            name="code",
            field=models.CharField(
                help_text="Required code for this category",
                max_length=50,
                verbose_name="code",
            ),
        ),
        migrations.AlterField(
            model_name="testcategory",
            name="name",
            field=models.CharField(
                db_index=True,
                help_text="Category name to group related test cases",
                max_length=50,
                unique=True,
                verbose_name="category Name",
            ),
        ),
        migrations.AlterField(
            model_name="testsuite",
            name="description",
            field=models.TextField(
                blank=True,
                help_text="Detailed description of what this test group does",
                verbose_name="Description",
            ),
        ),
        migrations.AlterField(
            model_name="testsuite",
            name="is_active",
            field=models.BooleanField(
                default=True,
                help_text="Whether this test group is currently active",
                verbose_name="Is Active",
            ),
        ),
        migrations.AlterField(
            model_name="testsuite",
            name="name",
            field=models.CharField(
                db_index=True,
                help_text="Descriptive name for the test group",
                max_length=50,
                verbose_name="Test Group Name",
            ),
        ),
        migrations.AlterField(
            model_name="testsuite",
            name="test_cases",
            field=models.ManyToManyField(
                help_text="Test cases included in this group",
                related_name="test_suites",
                through="test_management.TestSuiteCase",
                to=settings.TEST_MANAGEMENT_TESTCASE_MODEL,
                verbose_name="Test Cases",
            ),
        ),
        migrations.AlterField(
            model_name="testsuitecase",
            name="order",
            field=models.PositiveIntegerField(
                default=0,
                help_text="Execution order of test case within the group",
                verbose_name="order",
            ),
        ),
        migrations.AlterField(
            model_name="testsuitecase",
            name="test_case",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.TEST_MANAGEMENT_TESTCASE_MODEL,
                verbose_name="Test Case",
            ),
        ),
        migrations.AlterField(
            model_name="testsuitecase",
            name="test_suite",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.TEST_MANAGEMENT_TESTSUITE_MODEL,
                verbose_name="Test Group",
            ),
        ),
        migrations.AlterField(
            model_name="testsuiteexecution",
            name="test_suite",
            field=models.ForeignKey(
                help_text="Test to execute",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="executions",
                to=settings.TEST_MANAGEMENT_TESTSUITE_MODEL,
                verbose_name="Select Test Group",
            ),
        ),
        migrations.RemoveField(
            model_name="testsuite",
            name="category",
        ),
    ]
