# Generated by Django 5.2.3 on 2025-08-14 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "test_management",
            "0005_alter_testsuite_options_alter_testsuitecase_options_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="testsuiteexecutiondevice",
            name="allure_report_path",
            field=models.CharField(
                blank=True,
                help_text="Path to the Allure report HTML file for this device execution",
                max_length=255,
                verbose_name="allure report path",
            ),
        ),
        migrations.AlterField(
            model_name="testcase",
            name="description",
            field=models.TextField(
                blank=True,
                help_text="Detailed description of what this test does",
                max_length=1000,
                verbose_name="Description",
            ),
        ),
        migrations.AlterField(
            model_name="testcategory",
            name="code",
            field=models.CharField(
                help_text="Required code for this category",
                max_length=50,
                verbose_name="category Code",
            ),
        ),
        migrations.AlterField(
            model_name="testcategory",
            name="description",
            field=models.TextField(
                blank=True,
                help_text="Detailed description of what tests in this category do",
                max_length=1000,
                verbose_name="description",
            ),
        ),
        migrations.AlterField(
            model_name="testsuite",
            name="description",
            field=models.TextField(
                blank=True,
                help_text="Detailed description of what this test group does",
                max_length=1000,
                verbose_name="Description",
            ),
        ),
    ]
