# Generated by Django 5.2.3 on 2025-08-18 09:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "test_management",
            "0006_testsuiteexecutiondevice_allure_report_path_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="testsuitecase",
            name="test_suite",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="suite_cases",
                to=settings.TEST_MANAGEMENT_TESTSUITE_MODEL,
                verbose_name="Test Group",
            ),
        ),
    ]
