# Generated by Django 5.2.3 on 2025-08-21 10:56

import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
import openwisp_users.mixins
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("openwisp_users", "0021_rename_user_id_email_openwisp_us_id_06c07a_idx"),
        ("test_management", "0007_alter_testsuitecase_test_suite"),
        migrations.swappable_dependency(settings.CONFIG_DEVICE_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="TestDeviceGroup",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        db_index=True,
                        help_text="Name for the test device group (3-100 characters)",
                        max_length=100,
                        verbose_name="Group Name",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Description of this device group (max 500 characters)",
                        max_length=500,
                        verbose_name="Description",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="openwisp_users.organization",
                        verbose_name="organization",
                    ),
                ),
            ],
            options={
                "verbose_name": "Test Device Group",
                "verbose_name_plural": "Test Device Groups",
                "ordering": ["organization", "name"],
                "abstract": False,
                "swappable": "TEST_MANAGEMENT_TESTDEVICEGROUP_MODEL",
                "unique_together": {("name", "organization")},
            },
            bases=(openwisp_users.mixins.ValidateOrgMixin, models.Model),
        ),
        migrations.CreateModel(
            name="TestDeviceGroupDevice",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                (
                    "device",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="test_device_groups",
                        to=settings.CONFIG_DEVICE_MODEL,
                        verbose_name="Device",
                    ),
                ),
                (
                    "group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="devices",
                        to=settings.TEST_MANAGEMENT_TESTDEVICEGROUP_MODEL,
                        verbose_name="Test Device Group",
                    ),
                ),
            ],
            options={
                "verbose_name": "Test Device Group Device",
                "verbose_name_plural": "Test Device Group Devices",
                "ordering": ["group", "device"],
                "abstract": False,
                "swappable": "TEST_MANAGEMENT_TESTDEVICEGROUPDEVICE_MODEL",
                "default_permissions": (),
                "unique_together": {("group", "device")},
            },
        ),
    ]
