# Generated by Django 5.2.3 on 2025-08-22 10:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("test_management", "0008_testdevicegroup_testdevicegroupdevice"),
    ]

    operations = [
        migrations.AddField(
            model_name="testsuiteexecution",
            name="device_count",
            field=models.PositiveIntegerField(
                default=0,
                help_text="Number of devices in this execution",
                verbose_name="device count",
            ),
        ),
        migrations.AddField(
            model_name="testsuiteexecution",
            name="device_group",
            field=models.ForeignKey(
                blank=True,
                help_text="Device group for execution (required if device selection is 'Device Group')",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="test_executions",
                to=settings.TEST_MANAGEMENT_TESTDEVICEGROUP_MODEL,
                verbose_name="device group",
            ),
        ),
        migrations.AddField(
            model_name="testsuiteexecution",
            name="device_selection",
            field=models.IntegerField(
                choices=[(0, "Single Device Selection"), (1, "Device Group Selection")],
                default=0,
                help_text="Type of device selection: Single or Device Group",
                verbose_name="device selection type",
            ),
        ),
        migrations.AddField(
            model_name="testsuiteexecution",
            name="testcase_count",
            field=models.PositiveIntegerField(
                default=0,
                help_text="Number of test cases in this execution",
                verbose_name="test case count",
            ),
        ),
    ]
