# Generated by Django 5.2.3 on 2025-08-26 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("test_management", "0009_testsuiteexecution_device_count_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="testsuiteexecution",
            name="device_selection",
            field=models.IntegerField(
                choices=[(0, "Individual"), (1, "Device Group")],
                default=0,
                help_text="Type of device selection: Individual or Device Group",
                verbose_name="device selection type",
            ),
        ),
    ]
