# Generated by Django 5.2.3 on 2025-08-28 05:58

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("test_management", "0010_alter_testsuiteexecution_device_selection"),
    ]

    operations = [
        migrations.AddField(
            model_name="testsuiteexecution",
            name="name",
            field=models.CharField(
                db_index=True,
                default=django.utils.timezone.now,
                help_text="Descriptive name for the test Execution",
                max_length=50,
                verbose_name="Test Execution Name",
            ),
            preserve_default=False,
        ),
    ]
