# Generated by Django 5.2.3 on 2025-10-06 12:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("test_management", "0012_alter_testcaseexecution_status"),
    ]

    operations = [
        migrations.CreateModel(
            name="ScheduledExecution",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("scheduled_time", models.DateTimeField()),
                (
                    "status",
                    models.IntegerField(
                        choices=[(0, "Pending"), (1, "In Process"), (2, "Completed")],
                        default=0,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "execution",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="scheduled_executions",
                        to=settings.TEST_MANAGEMENT_TESTSUITEEXECUTION_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["scheduled_time"],
                "abstract": False,
                "swappable": "TEST_MANAGEMENT_SCHEDULEDEXECUTION_MODEL",
            },
        ),
    ]
