# Generated by Django 5.2.3 on 2025-10-15 06:02

import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
import openwisp_test_management.base.models
import private_storage.fields
import private_storage.storage.files
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("test_management", "0012_alter_testcaseexecution_status"),
    ]

    operations = [
        migrations.CreateModel(
            name="AbstractFileUpload",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        db_index=True,
                        help_text="Enter file name",
                        max_length=50,
                        unique=True,
                        verbose_name="File Name",
                    ),
                ),
                (
                    "file",
                    private_storage.fields.PrivateFileField(
                        max_length=255,
                        storage=private_storage.storage.files.PrivateFileSystemStorage(
                            base_url="/"
                        ),
                        upload_to=openwisp_test_management.base.models.get_build_directory,
                        verbose_name="File",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="FileUplaod",
            fields=[
                (
                    "abstractfileupload_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="test_management.abstractfileupload",
                    ),
                ),
            ],
            options={
                "abstract": False,
                "swappable": "TEST_MANAGEMENT_FILEUPLAOD_MODEL",
            },
            bases=("test_management.abstractfileupload",),
        ),
    ]
