# Generated by Django 5.2.3 on 2025-10-15 06:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("test_management", "0013_abstractfileupload_fileuplaod"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="FileUplaod",
            new_name="FileUpload",
        ),
    ]
