# Generated by Django 5.2.3 on 2025-10-09 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("test_management", "0013_scheduledexecution"),
    ]

    operations = [
        migrations.AddField(
            model_name="scheduledexecution",
            name="celery_task_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="scheduledexecution",
            name="completed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="scheduledexecution",
            name="error_message",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="scheduledexecution",
            name="queued_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="scheduledexecution",
            name="retry_count",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="scheduledexecution",
            name="started_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="scheduledexecution",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="scheduledexecution",
            name="status",
            field=models.IntegerField(
                choices=[
                    (0, "Pending"),
                    (1, "Queued"),
                    (2, "In Process"),
                    (3, "Completed"),
                    (4, "Failed"),
                    (5, "Cancelled"),
                ],
                default=0,
            ),
        ),
        migrations.AddIndex(
            model_name="scheduledexecution",
            index=models.Index(
                fields=["status", "scheduled_time"],
                name="test_manage_status_53ff7a_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="scheduledexecution",
            index=models.Index(
                fields=["celery_task_id"], name="test_manage_celery__dd8d66_idx"
            ),
        ),
    ]
