# Generated by Django 5.2.3 on 2025-10-15 09:16

import openwisp_test_management.base.models
import private_storage.fields
import private_storage.storage.files
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("test_management", "0014_rename_fileuplaod_fileupload"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="fileupload",
            name="abstractfileupload_ptr",
        ),
        migrations.AddField(
            model_name="testcase",
            name="file",
            field=private_storage.fields.PrivateFileField(
                help_text="Upload Test Script file.",
                max_length=255,
                null=True,
                storage=private_storage.storage.files.PrivateFileSystemStorage(
                    base_url="/",
                    location="/home/spanidea-lt83/Desktop/nokia/openwisp-controller/tests/openwisp_test_management/private_storage/stored_data",
                ),
                upload_to=openwisp_test_management.base.models.get_build_directory,
                verbose_name="Test Script",
            ),
        ),
        migrations.DeleteModel(
            name="AbstractFileUpload",
        ),
        migrations.DeleteModel(
            name="FileUpload",
        ),
    ]
