# Generated by Django 5.2.3 on 2025-10-31 11:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("test_management", "0014_scheduledexecution_celery_task_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="testsuiteexecution",
            name="individual_test_cases",
            field=models.ManyToManyField(
                blank=True,
                help_text="Individual test cases to execute (required if selection type is 'Individual Test Cases')",
                related_name="individual_executions",
                to=settings.TEST_MANAGEMENT_TESTCASE_MODEL,
                verbose_name="Select Test Cases",
            ),
        ),
        migrations.AddField(
            model_name="testsuiteexecution",
            name="test_selection_type",
            field=models.IntegerField(
                choices=[(0, "Individual Test Cases"), (1, "Test Suite")],
                db_index=True,
                default=1,
                help_text="Select individual test cases or a test suite",
                verbose_name="test selection type",
            ),
        ),
        migrations.AlterField(
            model_name="testsuiteexecution",
            name="test_suite",
            field=models.ForeignKey(
                blank=True,
                help_text="Test suite to execute (required if selection type is 'Test Suite')",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="executions",
                to=settings.TEST_MANAGEMENT_TESTSUITE_MODEL,
                verbose_name="Select Test Group",
            ),
        ),
    ]
