# Generated by Django 5.2.3 on 2025-11-04 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("test_management", "0015_testsuiteexecution_individual_test_cases_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="testsuiteexecutiondevice",
            name="connection_protocol",
            field=models.IntegerField(
                choices=[(0, "MQTT"), (1, "SSH")],
                default=0,
                help_text="connection protocol used by device to run testcases.",
                verbose_name="Connection Protocol",
            ),
        ),
    ]
