# Generated by Django 5.2.3 on 2025-11-09 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("test_management", "0016_testsuiteexecutiondevice_connection_protocol"),
    ]

    operations = [
        migrations.AlterField(
            model_name="testcaseexecution",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("running", "Running"),
                    ("success", "Passed"),
                    ("failed", "Failed"),
                    ("timeout", "Timeout"),
                    ("cancelled", "Cancelled"),
                    ("aborting", "Aborting"),
                    ("aborted", "Aborted"),
                ],
                db_index=True,
                default="pending",
                help_text="Current execution status",
                max_length=20,
                verbose_name="status",
            ),
        ),
    ]
