# Generated by Django 5.2.3 on 2025-11-14 07:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("test_management", "0017_alter_testcaseexecution_status"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="testsuiteexecution",
            options={
                "ordering": ["-created"],
                "verbose_name": "Test Execution",
                "verbose_name_plural": "Test Executions",
            },
        ),
    ]
