# Generated by Django 5.2.3 on 2025-11-16 17:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("test_management", "0018_alter_testsuiteexecution_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="testsuiteexecutiondevice",
            options={
                "default_permissions": (),
                "ordering": ["test_suite_execution", "device"],
                "verbose_name": "Test Group Execution Device",
                "verbose_name_plural": "Test Group Execution Devices",
            },
        ),
        migrations.AlterField(
            model_name="testcase",
            name="test_type",
            field=models.IntegerField(
                choices=[(1, "Robot Framework"), (2, "Device")],
                default=1,
                help_text="Type of test: Robot Framework or Device",
                verbose_name="Test Type",
            ),
        ),
        migrations.AlterField(
            model_name="testcaseexecution",
            name="test_suite_execution",
            field=models.ForeignKey(
                help_text="The parent test group execution",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="test_case_executions",
                to=settings.TEST_MANAGEMENT_TESTSUITEEXECUTION_MODEL,
                verbose_name="test group execution",
            ),
        ),
        migrations.AlterField(
            model_name="testsuiteexecution",
            name="test_selection_type",
            field=models.IntegerField(
                choices=[(0, "Individual"), (1, "Group")],
                db_index=True,
                default=1,
                help_text="Select individual test cases or a test Group",
                verbose_name="test selection type",
            ),
        ),
        migrations.AlterField(
            model_name="testsuiteexecution",
            name="test_suite",
            field=models.ForeignKey(
                blank=True,
                help_text="Test Group to execute (required if selection type is 'Test Group')",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="executions",
                to=settings.TEST_MANAGEMENT_TESTSUITE_MODEL,
                verbose_name="Select Test Group",
            ),
        ),
        migrations.AlterField(
            model_name="testsuiteexecutiondevice",
            name="test_suite_execution",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="devices",
                to=settings.TEST_MANAGEMENT_TESTSUITEEXECUTION_MODEL,
                verbose_name="test Group execution",
            ),
        ),
    ]
