# Generated by Django 5.2.3 on 2025-11-17 06:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("test_management", "0015_remove_fileupload_abstractfileupload_ptr_and_more"),
        ("test_management", "0019_alter_testsuiteexecutiondevice_options_and_more"),
    ]

    operations = []
