# Generated by Django 5.2.3 on 2025-11-17 06:51

import openwisp_test_management.base.models
import private_storage.fields
import private_storage.storage.files
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("test_management", "0020_merge_20251117_1149"),
    ]

    operations = [
        migrations.AlterField(
            model_name="testcase",
            name="file",
            field=private_storage.fields.PrivateFileField(
                help_text="Upload Test Script file.",
                max_length=255,
                null=True,
                storage=private_storage.storage.files.PrivateFileSystemStorage(
                    base_url="/media/", location="/opt/openwisp/media/test_case"
                ),
                upload_to=openwisp_test_management.base.models.get_build_directory,
                verbose_name="Test Script",
            ),
        ),
    ]
