# Generated by Django 5.2.3 on 2025-11-17 09:14

import private_storage.fields
import private_storage.storage.files
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("test_management", "0021_alter_testcase_file"),
    ]

    operations = [
        migrations.AlterField(
            model_name="testcase",
            name="file",
            field=private_storage.fields.PrivateFileField(
                help_text="Upload Test Script file.",
                max_length=255,
                null=True,
                storage=private_storage.storage.files.PrivateFileSystemStorage(
                    base_url="/media/", location="/opt/openwisp/media/zip"
                ),
                upload_to="zip/",
                verbose_name="Test Script",
            ),
        ),
    ]
