# Generated by Django 5.2.3 on 2025-11-19 07:23

import pathlib
import private_storage.fields
import private_storage.storage.files
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("test_management", "0022_alter_testcase_file"),
    ]

    operations = [
        migrations.AlterField(
            model_name="testcase",
            name="file",
            field=private_storage.fields.PrivateFileField(
                blank=True,
                help_text='<button type="button" class="guideline-btn" data-bs-toggle="modal" data-bs-target="#guidelineModal">Guidelines to Upload Test Scripts</button>',
                max_length=255,
                null=True,
                storage=private_storage.storage.files.PrivateFileSystemStorage(
                    base_url="/test-script-media/",
                    location=pathlib.PurePosixPath(
                        "/home/spanidea-lt83/Desktop/nokia/openwisp-controller/tests/media"
                    ),
                ),
                upload_to="zip/",
                verbose_name="Test Script",
            ),
        ),
    ]
