# Generated by Django 5.2.3 on 2025-11-19 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("test_management", "0023_alter_testcase_file"),
    ]

    operations = [
        migrations.AlterField(
            model_name="testcase",
            name="description",
            field=models.TextField(
                help_text="Detailed description of what this test does",
                max_length=10000,
                verbose_name="Description",
            ),
        ),
    ]
