# Generated by Django 5.2.3 on 2025-11-19 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("test_management", "0023_alter_testcase_file"),
    ]

    operations = [
        migrations.AddField(
            model_name="testcaseexecution",
            name="process_id",
            field=models.IntegerField(
                blank=True,
                help_text="Process ID returned by executor server.",
                null=True,
                verbose_name="Process ID",
            ),
        ),
    ]
