# Generated by Django 5.2.3 on 2025-11-19 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("test_management", "0024_alter_testcase_description"),
        ("test_management", "0024_testcaseexecution_process_id"),
    ]

    operations = []
