# Generated by Django 5.2.3 on 2025-11-26 09:23

import private_storage.fields
import private_storage.storage.files
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("test_management", "0025_merge_20251119_1748"),
    ]

    operations = [
        migrations.AlterField(
            model_name="testcase",
            name="file",
            field=private_storage.fields.PrivateFileField(
                blank=True,
                help_text='<button type="button" class="guideline-btn" data-bs-toggle="modal" data-bs-target="#guidelineModal">Guidelines to Upload Test Scripts</button>',
                max_length=255,
                null=True,
                storage=private_storage.storage.files.PrivateFileSystemStorage(
                    base_url="/test-script-media/", location="/opt/openwisp/media"
                ),
                upload_to="zip/",
                verbose_name="Test Script",
            ),
        ),
    ]
