# Generated by Django 5.2.3 on 2025-12-01 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("test_management", "0027_alter_testcase_file"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="testcase",
            name="file",
        ),
    ]
