# Generated by Django 5.2.3 on 2025-12-01 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("test_management", "0028_remove_testcase_file"),
    ]

    operations = [
        migrations.AddField(
            model_name="testcase",
            name="is_configuration_push_required",
            field=models.BooleanField(default=False),
        ),
    ]
