# Generated by Django 5.2.3 on 2025-12-01 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("test_management", "0029_testcase_is_configuration_push_required"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="testcase",
            name="is_configuration_push_required",
        ),
    ]
