# Generated by Django 5.2.3 on 2025-12-02 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("test_management", "0030_remove_testcase_is_configuration_push_required"),
    ]

    operations = [
        migrations.AddField(
            model_name="testcase",
            name="is_configuration_push_required",
            field=models.BooleanField(
                default=False,
                help_text="Whether a configuration push is required for this test case",
                verbose_name="Configuration Push Required",
            ),
        ),
    ]
