# Generated by Django 5.2.3 on 2025-12-07 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("test_management", "0031_testcase_is_configuration_push_required"),
    ]

    operations = [
        migrations.AlterField(
            model_name="testcase",
            name="is_configuration_push_required",
            field=models.BooleanField(
                default=False,
                help_text="Whether a file upload is required for this test case",
                verbose_name="Is File Required",
            ),
        ),
    ]
