# Generated by Django 5.2.3 on 2025-12-23 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("test_management", "0032_alter_testcase_is_configuration_push_required"),
    ]

    operations = [
        migrations.AlterField(
            model_name="testcategory",
            name="description",
            field=models.TextField(
                help_text="Detailed description of what tests in this category do",
                max_length=1000,
                verbose_name="description",
            ),
        ),
        migrations.AlterField(
            model_name="testdevicegroup",
            name="description",
            field=models.TextField(
                help_text="Description of this device group (max 500 characters)",
                max_length=500,
                verbose_name="Description",
            ),
        ),
        migrations.AlterField(
            model_name="testsuite",
            name="description",
            field=models.TextField(
                help_text="Detailed description of what this test group does",
                max_length=1000,
                verbose_name="Description",
            ),
        ),
    ]
