# Generated by Django 5.2.3 on 2025-12-16 07:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("test_management", "0032_alter_testcase_is_configuration_push_required"),
        migrations.swappable_dependency(settings.CONFIG_DEVICE_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AbstractExecutionArtifact",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("config_file", models.FileField(upload_to="execution_artifacts/")),
                ("is_pushed", models.BooleanField(default=False)),
                (
                    "device",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.CONFIG_DEVICE_MODEL,
                    ),
                ),
                (
                    "execution",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="artifacts",
                        to=settings.TEST_MANAGEMENT_TESTSUITEEXECUTION_MODEL,
                    ),
                ),
                (
                    "testcase",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.TEST_MANAGEMENT_TESTCASE_MODEL,
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("execution", "device", "testcase"),
                        name="uniq_execution_device_testcase",
                    )
                ],
            },
        ),
    ]
