# Generated by Django 5.2.3 on 2025-12-31 15:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("test_management", "0032_alter_testcase_is_configuration_push_required"),
    ]

    operations = [
        migrations.AddField(
            model_name="testsuiteexecution",
            name="parent_execution",
            field=models.ForeignKey(
                blank=True,
                help_text="Original execution if this is a re-execution",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="re_executions",
                to=settings.TEST_MANAGEMENT_TESTSUITEEXECUTION_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="testsuiteexecution",
            name="re_execution_index",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="1 for first re-execution, 2 for second, etc.",
                null=True,
            ),
        ),
    ]
