# Generated by Django 5.2.3 on 2025-12-23 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("test_management", "0033_alter_testcategory_description_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="testsuiteexecution",
            name="test_case_execution_order",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
