# Generated by Django 5.2.3 on 2026-01-12 06:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("test_management", "0033_executionartifact"),
        ("test_management", "0034_testsuiteexecution_test_case_execution_order"),
    ]

    operations = []
