# Generated by Django 5.2.3 on 2025-12-30 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("test_management", "0034_testsuiteexecution_test_case_execution_order"),
    ]

    operations = [
        migrations.AddField(
            model_name="testcase",
            name="python_script",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="test_scripts",
                verbose_name="Python Script",
            ),
        ),
        migrations.AddField(
            model_name="testcase",
            name="robot_script",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="test_scripts",
                verbose_name="Robot Script",
            ),
        ),
    ]
