# Generated by Django 5.2.3 on 2026-01-08 11:28

import openwisp_test_management.base.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("test_management", "0035_testcase_python_script_testcase_robot_script"),
    ]

    operations = [
        migrations.AddField(
            model_name="testcase",
            name="script_push_status",
            field=models.IntegerField(
                choices=[(0, "Pending"), (1, "Completed"), (2, "Failed")], default=0
            ),
        ),
        migrations.AlterField(
            model_name="testcase",
            name="python_script",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to=openwisp_test_management.base.models.rename_script,
                verbose_name="Python Script",
            ),
        ),
        migrations.AlterField(
            model_name="testcase",
            name="robot_script",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to=openwisp_test_management.base.models.rename_script,
                verbose_name="Robot Script",
            ),
        ),
    ]
