# Generated by Django 5.2.3 on 2026-01-12 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("test_management", "0035_merge_20260112_1138"),
    ]

    operations = [
        migrations.AddField(
            model_name="testsuiteexecution",
            name="completion_email_sent",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="testsuiteexecution",
            name="notification_emails",
            field=models.TextField(
                blank=True, help_text="Comma-separated email addresses"
            ),
        ),
    ]
