# Generated by Django 5.2.3 on 2026-01-13 06:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("test_management", "0036_testsuiteexecution_completion_email_sent_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="testsuiteexecution",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_test_executions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="testsuiteexecution",
            name="execution_start_time",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="testsuiteexecution",
            name="execution_status",
            field=models.IntegerField(
                choices=[
                    (0, "Created"),
                    (1, "Execution Progress"),
                    (2, "Partially Completed"),
                    (3, "Completed"),
                ],
                default=0,
                help_text="execution status",
                verbose_name="Execution Status",
            ),
        ),
    ]
