# Generated by Django 5.2.3 on 2026-01-09 08:22

import openwisp_test_management.base.models
import openwisp_test_management.private_storage.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("test_management", "0036_testcase_script_push_status_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="testcase",
            name="python_script",
            field=models.FileField(
                blank=True,
                null=True,
                storage=openwisp_test_management.private_storage.storage.OverwriteStorage(),
                upload_to=openwisp_test_management.base.models.rename_script,
                verbose_name="Python Script",
            ),
        ),
        migrations.AlterField(
            model_name="testcase",
            name="robot_script",
            field=models.FileField(
                blank=True,
                null=True,
                storage=openwisp_test_management.private_storage.storage.OverwriteStorage(),
                upload_to=openwisp_test_management.base.models.rename_script,
                verbose_name="Robot Script",
            ),
        ),
    ]
