# Generated by Django 5.2.3 on 2026-01-12 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("test_management", "0035_merge_20260107_2319"),
        ("test_management", "0037_alter_testcase_python_script_and_more"),
    ]

    operations = []
