# Generated by Django 5.2.3 on 2026-01-17 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("test_management", "0033_testsuiteexecution_parent_execution_and_more"),
        ("test_management", "0037_testsuiteexecution_created_by_and_more"),
        ("test_management", "0038_merge_20260112_2357"),
    ]

    operations = []
