# Generated by Django 5.2.3 on 2026-01-17 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("test_management", "0040_testcase_created_by"),
    ]

    operations = [
        migrations.AddField(
            model_name="testsuiteexecution",
            name="completion_notification_sent",
            field=models.BooleanField(default=False),
        ),
    ]
