# Generated by Django 5.2.3 on 2026-01-18 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("test_management", "0039_merge_20260116_1822"),
        ("test_management", "0041_testsuiteexecution_completion_notification_sent"),
    ]

    operations = []
