# Generated by Django 5.2.3 on 2026-01-20 04:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("test_management", "0042_merge_20260118_2309"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="testcase",
            unique_together=set(),
        ),
    ]
