# Generated by Django 5.2.3 on 2026-01-22 13:28

import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("test_management", "0044_testsuite_created_by"),
    ]

    operations = [
        migrations.CreateModel(
            name="ExecutionEmailLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                (
                    "email_address",
                    models.EmailField(
                        db_index=True, max_length=254, verbose_name="Email Address"
                    ),
                ),
                (
                    "status",
                    models.IntegerField(
                        choices=[
                            (0, "Pending"),
                            (1, "Queued"),
                            (2, "Sent"),
                            (3, "Failed"),
                            (4, "Retry"),
                        ],
                        default=0,
                        verbose_name="Status",
                    ),
                ),
                (
                    "celery_task_id",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Celery Task ID",
                    ),
                ),
                (
                    "attempt_count",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Attempt Count"
                    ),
                ),
                (
                    "last_attempt_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Last Attempt At"
                    ),
                ),
                (
                    "sent_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="Sent At"),
                ),
                (
                    "error_message",
                    models.TextField(blank=True, verbose_name="Error Message"),
                ),
                (
                    "execution",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="email_logs",
                        to=settings.TEST_MANAGEMENT_TESTSUITEEXECUTION_MODEL,
                        verbose_name="Test Execution",
                    ),
                ),
            ],
            options={
                "verbose_name": "Execution Email Log",
                "verbose_name_plural": "Execution Email Logs",
                "abstract": False,
                "swappable": "TEST_MANAGEMENT_EXECUTIONEMAILLOG_MODEL",
                "indexes": [
                    models.Index(
                        fields=["execution", "status"],
                        name="test_manage_executi_3bcf4d_idx",
                    ),
                    models.Index(
                        fields=["status", "last_attempt_at"],
                        name="test_manage_status_734bd2_idx",
                    ),
                ],
                "unique_together": {("execution", "email_address")},
            },
        ),
    ]
