# Generated by Django 5.2.3 on 2026-02-13 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("test_management", "0045_executionemaillog"),
    ]

    operations = [
        migrations.AlterField(
            model_name="testcase",
            name="test_type",
            field=models.IntegerField(
                choices=[(1, "Robot Framework"), (2, "Device")],
                default=1,
                help_text="Type of test: Robot Framework (1) or Device (2)",
                verbose_name="Test Type",
            ),
        ),
    ]
