# Generated by Django 5.2.3 on 2026-02-18 06:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("test_management", "0046_alter_testcase_test_type"),
        ("test_management", "0046_testcase_is_system_test_case_and_more"),
    ]

    operations = []
