# Generated by Django 5.2.3 on 2025-06-17 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("testmanagement", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="TestGroup",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name_text", models.CharField(default="", max_length=200)),
                ("description_text", models.CharField(default="", max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name="TestSuite",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name_text", models.CharField(default="", max_length=200)),
                ("description_text", models.CharField(default="", max_length=200)),
            ],
        ),
        migrations.RemoveField(
            model_name="testcase",
            name="id",
        ),
        migrations.AddField(
            model_name="testcase",
            name="enabled",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="testcase",
            name="name_text",
            field=models.CharField(default="", max_length=200),
        ),
        migrations.AddField(
            model_name="testcase",
            name="testcase_id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="testcase",
            name="description_text",
            field=models.CharField(default="", max_length=200),
        ),
        migrations.AlterField(
            model_name="testcase",
            name="input_text",
            field=models.CharField(default="", max_length=200),
        ),
    ]
