# Generated by Django 5.2.3 on 2025-06-17 10:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("testmanagement", "0002_testgroup_testsuite_remove_testcase_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="testcase",
            name="testsuite",
            field=models.ForeignKey(
                default="",
                on_delete=django.db.models.deletion.CASCADE,
                to="testmanagement.testsuite",
            ),
        ),
        migrations.AlterField(
            model_name="testcase",
            name="input_text",
            field=models.TextField(),
        ),
    ]
