# Generated by Django 5.2.3 on 2025-06-17 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("testmanagement", "0003_testcase_testsuite_alter_testcase_input_text"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="testcase",
            name="testsuite",
        ),
        migrations.AddField(
            model_name="testcase",
            name="testsuite",
            field=models.ManyToManyField(to="testmanagement.testsuite"),
        ),
    ]
