# Generated by Django 5.2.3 on 2025-06-17 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("testmanagement", "0004_remove_testcase_testsuite_testcase_testsuite"),
    ]

    operations = [
        migrations.AlterField(
            model_name="testcase",
            name="testsuite",
            field=models.ManyToManyField(null=True, to="testmanagement.testsuite"),
        ),
    ]
