# Generated by Django 5.2.3 on 2025-06-17 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("testmanagement", "0005_alter_testcase_testsuite"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="testcase",
            name="testsuite",
        ),
    ]
