# Generated by Django 5.2.3 on 2025-06-18 06:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("testmanagement", "0008_alter_testcase_testsuite"),
    ]

    operations = [
        migrations.RenameField(
            model_name="testcase",
            old_name="description_text",
            new_name="description",
        ),
        migrations.RenameField(
            model_name="testcase",
            old_name="input_text",
            new_name="input",
        ),
        migrations.RenameField(
            model_name="testcase",
            old_name="name_text",
            new_name="name",
        ),
        migrations.RenameField(
            model_name="testsuite",
            old_name="description_text",
            new_name="description",
        ),
        migrations.RenameField(
            model_name="testsuite",
            old_name="name_text",
            new_name="name",
        ),
    ]
