# Generated by Django 5.2.3 on 2025-06-18 06:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "testmanagement",
            "0009_rename_description_text_testcase_description_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="testcase",
            name="testsuite",
        ),
        migrations.AddField(
            model_name="testcase",
            name="testsuite",
            field=models.ForeignKey(
                default="",
                on_delete=django.db.models.deletion.CASCADE,
                to="testmanagement.testsuite",
            ),
            preserve_default=False,
        ),
    ]
