# Generated by Django 5.2.3 on 2025-06-18 08:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("testmanagement", "0010_remove_testcase_testsuite_testcase_testsuite"),
    ]

    operations = [
        migrations.RenameField(
            model_name="testgroup",
            old_name="description_text",
            new_name="description",
        ),
        migrations.RenameField(
            model_name="testgroup",
            old_name="name_text",
            new_name="name",
        ),
    ]
