# Generated by Django 5.2.3 on 2025-06-18 08:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "testmanagement",
            "0011_rename_description_text_testgroup_description_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="TestSuiteCase",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(default="", max_length=200)),
                ("description", models.CharField(default="", max_length=200)),
            ],
        ),
        migrations.RenameModel(
            old_name="TestGroup",
            new_name="TestCategory",
        ),
        migrations.DeleteModel(
            name="TestModel",
        ),
        migrations.AddField(
            model_name="testsuite",
            name="testsuitecase",
            field=models.ForeignKey(
                default="",
                on_delete=django.db.models.deletion.CASCADE,
                to="testmanagement.testsuitecase",
            ),
            preserve_default=False,
        ),
    ]
