# Generated by Django 5.2.3 on 2025-06-19 10:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("testmanagement", "0012_testsuitecase_rename_testgroup_testcategory_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="testcase",
            name="testsuite",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="testcases",
                to="testmanagement.testsuite",
            ),
        ),
    ]
